/**
 * Cloudflare Worker entry. OpenNext serves the Next.js app through `fetch`;
 * `scheduled` turns Cron Triggers into calls to our job routes (one small
 * batch each). Job logic lives in src/ where it is typed and tested; keep
 * this file as thin glue. Never log secrets or personal data here.
 */
// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and has no types.
import { default as generated } from "./.open-next/worker.js";

import { CRON_SECRET_HEADER, jobsForCron } from "./src/lib/jobs/schedule";

interface Env {
  CRON_SECRET?: string;
}

interface FetchHandler {
  fetch(request: Request, env: Env, ctx: WaitUntil): Promise<Response>;
}

const handler = generated as FetchHandler;

interface ScheduledController {
  cron: string;
}

interface WaitUntil {
  waitUntil(promise: Promise<unknown>): void;
}

const worker = {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledController, env: Env, ctx: WaitUntil) {
    const secret = env.CRON_SECRET;
    if (!secret) return; // Not configured yet: do nothing.
    const jobs = jobsForCron(controller.cron);
    // Jobs run one after another: a later job may depend on an earlier one.
    // Each is called in-process (no network round trip, no extra request).
    // Logs carry only the job name and status code, never payloads or secrets.
    const run = async () => {
      for (const job of jobs) {
        const request = new Request(`https://cron.internal/api/jobs/${job}`, {
          method: "POST",
          headers: { [CRON_SECRET_HEADER]: secret },
        });
        try {
          const response = await handler.fetch(request, env, ctx);
          console.log(`job ${job}: ${response.status}`);
        } catch {
          console.error(`job ${job}: failed`);
        }
      }
    };
    ctx.waitUntil(run());
  },
};

export default worker;
